from typing import Protocol

from packages.database.models import (
    Analysis,
    ArtifactReference,
    AuditEvent,
    Cohort,
    DatasetObject,
    DatasetSnapshot,
    Finding,
    Job,
    Materialization,
    MaterializationSource,
    Project,
)


class ProjectRepository(Protocol):
    def get(self, project_id: str) -> Project | None: ...
    def list(self, *, limit: int, offset: int) -> list[Project]: ...
    def save(self, project: Project) -> Project: ...


class SnapshotRepository(Protocol):
    def get(self, snapshot_id: str) -> DatasetSnapshot | None: ...
    def list(self, *, project_id: str | None, limit: int, offset: int) -> list[DatasetSnapshot]: ...
    def save(self, snapshot: DatasetSnapshot) -> DatasetSnapshot: ...


class ArtifactRepository(Protocol):
    def get(self, sha256: str) -> DatasetObject | None: ...
    def save(self, artifact: DatasetObject) -> DatasetObject: ...
    def list_for_snapshot(self, snapshot_id: str) -> list[ArtifactReference]: ...
    def by_snapshot_role(self, snapshot_id: str) -> dict[str, ArtifactReference]: ...


class MaterializationRepository(Protocol):
    def get(self, materialization_id: str) -> Materialization | None: ...
    def get_source(self, source_id: str) -> MaterializationSource | None: ...
    def list(
        self, snapshot_id: str, modality: str, measurement_type: str
    ) -> list[Materialization]: ...


class CohortRepository(Protocol):
    def get(self, cohort_id: str) -> Cohort | None: ...
    def list(self, *, snapshot_id: str | None, limit: int, offset: int) -> list[Cohort]: ...
    def save(self, cohort: Cohort) -> Cohort: ...


class AnalysisRepository(Protocol):
    def get(self, analysis_id: str) -> Analysis | None: ...
    def save(self, analysis: Analysis) -> Analysis: ...


class FindingRepository(Protocol):
    def get(self, finding_id: str) -> Finding | None: ...
    def save(self, finding: Finding) -> Finding: ...


class AuditRepository(Protocol):
    def append(self, event: AuditEvent) -> AuditEvent: ...


class JobRepository(Protocol):
    def save(self, job: Job) -> Job: ...
